/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AudioId = IDL.Text;
export const VideoId = IDL.Text;
export const AudioMetadata = IDL.Record({
  'id' : AudioId,
  'duration' : IDL.Nat,
  'createdBy' : IDL.Principal,
  'language' : IDL.Text,
  'speakerId' : IDL.Principal,
  'uploadDate' : IDL.Int,
  'videoId' : VideoId,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Audio = IDL.Record({
  'metadata' : AudioMetadata,
  'audioBlob' : ExternalBlob,
});
export const MusicId = IDL.Text;
export const BackgroundMusicMetadata = IDL.Record({
  'id' : MusicId,
  'duration' : IDL.Nat,
  'createdBy' : IDL.Principal,
  'genre' : IDL.Text,
  'uploadDate' : IDL.Int,
  'videoId' : VideoId,
});
export const BackgroundMusic = IDL.Record({
  'metadata' : BackgroundMusicMetadata,
  'musicBlob' : ExternalBlob,
});
export const EmotionId = IDL.Text;
export const Emotion = IDL.Record({
  'id' : EmotionId,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'uploadDate' : IDL.Int,
  'intensityRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
});
export const GestureId = IDL.Text;
export const Gesture = IDL.Record({
  'id' : GestureId,
  'animationClip' : ExternalBlob,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'uploadDate' : IDL.Int,
});
export const SceneConfigId = IDL.Text;
export const SceneConfig = IDL.Record({
  'id' : SceneConfigId,
  'createdBy' : IDL.Principal,
  'sceneData' : IDL.Text,
  'uploadDate' : IDL.Int,
  'videoId' : VideoId,
});
export const VisualEffectType = IDL.Variant({
  'particle' : IDL.Null,
  'lighting' : IDL.Null,
  'colorGrading' : IDL.Null,
  'depth' : IDL.Null,
  'reflection' : IDL.Null,
});
export const VisualEffect = IDL.Record({
  'startTime' : IDL.Nat,
  'duration' : IDL.Nat,
  'effectType' : VisualEffectType,
  'intensity' : IDL.Nat,
});
export const VideoFormat = IDL.Record({
  'codec' : IDL.Text,
  'compatibleBrowsers' : IDL.Vec(IDL.Text),
  'mimeType' : IDL.Text,
  'resolution' : IDL.Tuple(IDL.Nat, IDL.Nat),
  'extension' : IDL.Text,
  'bitrate' : IDL.Nat,
});
export const VideoMetadata = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'visuals' : IDL.Vec(VisualEffect),
  'uploadDate' : IDL.Int,
  'format' : VideoFormat,
});
export const Video = IDL.Record({
  'metadata' : VideoMetadata,
  'videoBlob' : ExternalBlob,
});
export const AvatarId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EmotionTimeline = IDL.Record({
  'emotion' : IDL.Text,
  'time' : IDL.Float64,
  'intensity' : IDL.Float64,
});
export const GestureCue = IDL.Record({
  'time' : IDL.Float64,
  'gesture' : IDL.Text,
});
export const AvatarMetadata = IDL.Record({
  'id' : AvatarId,
  'isValidated' : IDL.Bool,
  'validationResults' : IDL.Text,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'filePath' : IDL.Text,
  'uploadDate' : IDL.Int,
});
export const Avatar = IDL.Record({
  'avatarMetadata' : AvatarMetadata,
  'fileBlob' : ExternalBlob,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'avatarId' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAudio' : IDL.Func([Audio], [], []),
  'addBackgroundMusic' : IDL.Func([BackgroundMusic], [], []),
  'addEmotion' : IDL.Func([Emotion], [], []),
  'addGesture' : IDL.Func([Gesture], [], []),
  'addSceneConfig' : IDL.Func([SceneConfig], [], []),
  'addVideo' : IDL.Func([Video], [], []),
  'assignAvatarToUser' : IDL.Func([IDL.Principal, AvatarId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAvatar' : IDL.Func([AvatarId], [], []),
  'findVideosByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'generateEmotionTimeline' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EmotionTimeline)],
      [],
    ),
  'generateGestureTimeline' : IDL.Func([IDL.Text], [IDL.Vec(GestureCue)], []),
  'getAllAudioSorted' : IDL.Func([], [IDL.Vec(Audio)], ['query']),
  'getAllAvatars' : IDL.Func([], [IDL.Vec(Avatar)], ['query']),
  'getAllEmotions' : IDL.Func([], [IDL.Vec(Emotion)], ['query']),
  'getAllGestures' : IDL.Func([], [IDL.Vec(Gesture)], ['query']),
  'getAllMusicSorted' : IDL.Func([], [IDL.Vec(BackgroundMusic)], ['query']),
  'getAllSceneConfigsSorted' : IDL.Func([], [IDL.Vec(SceneConfig)], ['query']),
  'getAllVideosSorted' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getAudio' : IDL.Func([AudioId], [Audio], ['query']),
  'getAudioByCreator' : IDL.Func([IDL.Principal], [IDL.Vec(Audio)], ['query']),
  'getAvailableEmotions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAvailableGestures' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAvatar' : IDL.Func([AvatarId], [IDL.Opt(Avatar)], ['query']),
  'getBackgroundMusic' : IDL.Func([MusicId], [BackgroundMusic], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmotion' : IDL.Func([EmotionId], [IDL.Opt(Emotion)], ['query']),
  'getGesture' : IDL.Func([GestureId], [IDL.Opt(Gesture)], ['query']),
  'getGestureAnimation' : IDL.Func([GestureId], [ExternalBlob], ['query']),
  'getMusicByCreator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(BackgroundMusic)],
      ['query'],
    ),
  'getSceneConfig' : IDL.Func([SceneConfigId], [SceneConfig], ['query']),
  'getSceneConfigsByCreator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SceneConfig)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([VideoId], [Video], ['query']),
  'getVideosByCreator' : IDL.Func([IDL.Principal], [IDL.Vec(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processAvatarUpload' : IDL.Func(
      [AvatarMetadata, ExternalBlob],
      [Avatar],
      [],
    ),
  'registerAvatar' : IDL.Func([Avatar], [], []),
  'removeAssignedAvatar' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAudioMetadata' : IDL.Func([AudioId, AudioMetadata], [], []),
  'updateEmotion' : IDL.Func([EmotionId, Emotion], [], []),
  'updateGesture' : IDL.Func([GestureId, Gesture], [], []),
  'updateMusicMetadata' : IDL.Func([MusicId, BackgroundMusicMetadata], [], []),
  'updateSceneConfig' : IDL.Func([SceneConfigId, SceneConfig], [], []),
  'updateVideoMetadata' : IDL.Func([VideoId, VideoMetadata], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AudioId = IDL.Text;
  const VideoId = IDL.Text;
  const AudioMetadata = IDL.Record({
    'id' : AudioId,
    'duration' : IDL.Nat,
    'createdBy' : IDL.Principal,
    'language' : IDL.Text,
    'speakerId' : IDL.Principal,
    'uploadDate' : IDL.Int,
    'videoId' : VideoId,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Audio = IDL.Record({
    'metadata' : AudioMetadata,
    'audioBlob' : ExternalBlob,
  });
  const MusicId = IDL.Text;
  const BackgroundMusicMetadata = IDL.Record({
    'id' : MusicId,
    'duration' : IDL.Nat,
    'createdBy' : IDL.Principal,
    'genre' : IDL.Text,
    'uploadDate' : IDL.Int,
    'videoId' : VideoId,
  });
  const BackgroundMusic = IDL.Record({
    'metadata' : BackgroundMusicMetadata,
    'musicBlob' : ExternalBlob,
  });
  const EmotionId = IDL.Text;
  const Emotion = IDL.Record({
    'id' : EmotionId,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'uploadDate' : IDL.Int,
    'intensityRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
  });
  const GestureId = IDL.Text;
  const Gesture = IDL.Record({
    'id' : GestureId,
    'animationClip' : ExternalBlob,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'uploadDate' : IDL.Int,
  });
  const SceneConfigId = IDL.Text;
  const SceneConfig = IDL.Record({
    'id' : SceneConfigId,
    'createdBy' : IDL.Principal,
    'sceneData' : IDL.Text,
    'uploadDate' : IDL.Int,
    'videoId' : VideoId,
  });
  const VisualEffectType = IDL.Variant({
    'particle' : IDL.Null,
    'lighting' : IDL.Null,
    'colorGrading' : IDL.Null,
    'depth' : IDL.Null,
    'reflection' : IDL.Null,
  });
  const VisualEffect = IDL.Record({
    'startTime' : IDL.Nat,
    'duration' : IDL.Nat,
    'effectType' : VisualEffectType,
    'intensity' : IDL.Nat,
  });
  const VideoFormat = IDL.Record({
    'codec' : IDL.Text,
    'compatibleBrowsers' : IDL.Vec(IDL.Text),
    'mimeType' : IDL.Text,
    'resolution' : IDL.Tuple(IDL.Nat, IDL.Nat),
    'extension' : IDL.Text,
    'bitrate' : IDL.Nat,
  });
  const VideoMetadata = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'visuals' : IDL.Vec(VisualEffect),
    'uploadDate' : IDL.Int,
    'format' : VideoFormat,
  });
  const Video = IDL.Record({
    'metadata' : VideoMetadata,
    'videoBlob' : ExternalBlob,
  });
  const AvatarId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EmotionTimeline = IDL.Record({
    'emotion' : IDL.Text,
    'time' : IDL.Float64,
    'intensity' : IDL.Float64,
  });
  const GestureCue = IDL.Record({ 'time' : IDL.Float64, 'gesture' : IDL.Text });
  const AvatarMetadata = IDL.Record({
    'id' : AvatarId,
    'isValidated' : IDL.Bool,
    'validationResults' : IDL.Text,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'filePath' : IDL.Text,
    'uploadDate' : IDL.Int,
  });
  const Avatar = IDL.Record({
    'avatarMetadata' : AvatarMetadata,
    'fileBlob' : ExternalBlob,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'avatarId' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAudio' : IDL.Func([Audio], [], []),
    'addBackgroundMusic' : IDL.Func([BackgroundMusic], [], []),
    'addEmotion' : IDL.Func([Emotion], [], []),
    'addGesture' : IDL.Func([Gesture], [], []),
    'addSceneConfig' : IDL.Func([SceneConfig], [], []),
    'addVideo' : IDL.Func([Video], [], []),
    'assignAvatarToUser' : IDL.Func([IDL.Principal, AvatarId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAvatar' : IDL.Func([AvatarId], [], []),
    'findVideosByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'generateEmotionTimeline' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EmotionTimeline)],
        [],
      ),
    'generateGestureTimeline' : IDL.Func([IDL.Text], [IDL.Vec(GestureCue)], []),
    'getAllAudioSorted' : IDL.Func([], [IDL.Vec(Audio)], ['query']),
    'getAllAvatars' : IDL.Func([], [IDL.Vec(Avatar)], ['query']),
    'getAllEmotions' : IDL.Func([], [IDL.Vec(Emotion)], ['query']),
    'getAllGestures' : IDL.Func([], [IDL.Vec(Gesture)], ['query']),
    'getAllMusicSorted' : IDL.Func([], [IDL.Vec(BackgroundMusic)], ['query']),
    'getAllSceneConfigsSorted' : IDL.Func(
        [],
        [IDL.Vec(SceneConfig)],
        ['query'],
      ),
    'getAllVideosSorted' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getAudio' : IDL.Func([AudioId], [Audio], ['query']),
    'getAudioByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Audio)],
        ['query'],
      ),
    'getAvailableEmotions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAvailableGestures' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAvatar' : IDL.Func([AvatarId], [IDL.Opt(Avatar)], ['query']),
    'getBackgroundMusic' : IDL.Func([MusicId], [BackgroundMusic], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmotion' : IDL.Func([EmotionId], [IDL.Opt(Emotion)], ['query']),
    'getGesture' : IDL.Func([GestureId], [IDL.Opt(Gesture)], ['query']),
    'getGestureAnimation' : IDL.Func([GestureId], [ExternalBlob], ['query']),
    'getMusicByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(BackgroundMusic)],
        ['query'],
      ),
    'getSceneConfig' : IDL.Func([SceneConfigId], [SceneConfig], ['query']),
    'getSceneConfigsByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SceneConfig)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([VideoId], [Video], ['query']),
    'getVideosByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Video)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processAvatarUpload' : IDL.Func(
        [AvatarMetadata, ExternalBlob],
        [Avatar],
        [],
      ),
    'registerAvatar' : IDL.Func([Avatar], [], []),
    'removeAssignedAvatar' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAudioMetadata' : IDL.Func([AudioId, AudioMetadata], [], []),
    'updateEmotion' : IDL.Func([EmotionId, Emotion], [], []),
    'updateGesture' : IDL.Func([GestureId, Gesture], [], []),
    'updateMusicMetadata' : IDL.Func(
        [MusicId, BackgroundMusicMetadata],
        [],
        [],
      ),
    'updateSceneConfig' : IDL.Func([SceneConfigId, SceneConfig], [], []),
    'updateVideoMetadata' : IDL.Func([VideoId, VideoMetadata], [], []),
  });
};

export const init = ({ IDL }) => { return []; };