/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Audio {
  'metadata' : AudioMetadata,
  'audioBlob' : ExternalBlob,
}
export type AudioId = string;
export interface AudioMetadata {
  'id' : AudioId,
  'duration' : bigint,
  'createdBy' : Principal,
  'language' : string,
  'speakerId' : Principal,
  'uploadDate' : bigint,
  'videoId' : VideoId,
}
export interface Avatar {
  'avatarMetadata' : AvatarMetadata,
  'fileBlob' : ExternalBlob,
}
export type AvatarId = string;
export interface AvatarMetadata {
  'id' : AvatarId,
  'isValidated' : boolean,
  'validationResults' : string,
  'name' : string,
  'createdBy' : Principal,
  'description' : string,
  'filePath' : string,
  'uploadDate' : bigint,
}
export interface BackgroundMusic {
  'metadata' : BackgroundMusicMetadata,
  'musicBlob' : ExternalBlob,
}
export interface BackgroundMusicMetadata {
  'id' : MusicId,
  'duration' : bigint,
  'createdBy' : Principal,
  'genre' : string,
  'uploadDate' : bigint,
  'videoId' : VideoId,
}
export interface Emotion {
  'id' : EmotionId,
  'name' : string,
  'createdBy' : Principal,
  'description' : string,
  'uploadDate' : bigint,
  'intensityRange' : [bigint, bigint],
}
export type EmotionId = string;
export interface EmotionTimeline {
  'emotion' : string,
  'time' : number,
  'intensity' : number,
}
export type ExternalBlob = Uint8Array;
export interface Gesture {
  'id' : GestureId,
  'animationClip' : ExternalBlob,
  'name' : string,
  'createdBy' : Principal,
  'description' : string,
  'uploadDate' : bigint,
}
export interface GestureCue { 'time' : number, 'gesture' : string }
export type GestureId = string;
export type MusicId = string;
export interface SceneConfig {
  'id' : SceneConfigId,
  'createdBy' : Principal,
  'sceneData' : string,
  'uploadDate' : bigint,
  'videoId' : VideoId,
}
export type SceneConfigId = string;
export interface UserProfile { 'name' : string, 'avatarId' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'metadata' : VideoMetadata,
  'videoBlob' : ExternalBlob,
}
export interface VideoFormat {
  'codec' : string,
  'compatibleBrowsers' : Array<string>,
  'mimeType' : string,
  'resolution' : [bigint, bigint],
  'extension' : string,
  'bitrate' : bigint,
}
export type VideoId = string;
export interface VideoMetadata {
  'id' : VideoId,
  'title' : string,
  'duration' : bigint,
  'createdBy' : Principal,
  'description' : string,
  'visuals' : Array<VisualEffect>,
  'uploadDate' : bigint,
  'format' : VideoFormat,
}
export interface VisualEffect {
  'startTime' : bigint,
  'duration' : bigint,
  'effectType' : VisualEffectType,
  'intensity' : bigint,
}
export type VisualEffectType = { 'particle' : null } |
  { 'lighting' : null } |
  { 'colorGrading' : null } |
  { 'depth' : null } |
  { 'reflection' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAudio' : ActorMethod<[Audio], undefined>,
  'addBackgroundMusic' : ActorMethod<[BackgroundMusic], undefined>,
  'addEmotion' : ActorMethod<[Emotion], undefined>,
  'addGesture' : ActorMethod<[Gesture], undefined>,
  'addSceneConfig' : ActorMethod<[SceneConfig], undefined>,
  'addVideo' : ActorMethod<[Video], undefined>,
  'assignAvatarToUser' : ActorMethod<[Principal, AvatarId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAvatar' : ActorMethod<[AvatarId], undefined>,
  'findVideosByTitle' : ActorMethod<[string], Array<Video>>,
  'generateEmotionTimeline' : ActorMethod<[string], Array<EmotionTimeline>>,
  'generateGestureTimeline' : ActorMethod<[string], Array<GestureCue>>,
  'getAllAudioSorted' : ActorMethod<[], Array<Audio>>,
  'getAllAvatars' : ActorMethod<[], Array<Avatar>>,
  'getAllEmotions' : ActorMethod<[], Array<Emotion>>,
  'getAllGestures' : ActorMethod<[], Array<Gesture>>,
  'getAllMusicSorted' : ActorMethod<[], Array<BackgroundMusic>>,
  'getAllSceneConfigsSorted' : ActorMethod<[], Array<SceneConfig>>,
  'getAllVideosSorted' : ActorMethod<[], Array<Video>>,
  'getAudio' : ActorMethod<[AudioId], Audio>,
  'getAudioByCreator' : ActorMethod<[Principal], Array<Audio>>,
  'getAvailableEmotions' : ActorMethod<[], Array<string>>,
  'getAvailableGestures' : ActorMethod<[], Array<string>>,
  'getAvatar' : ActorMethod<[AvatarId], [] | [Avatar]>,
  'getBackgroundMusic' : ActorMethod<[MusicId], BackgroundMusic>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmotion' : ActorMethod<[EmotionId], [] | [Emotion]>,
  'getGesture' : ActorMethod<[GestureId], [] | [Gesture]>,
  'getGestureAnimation' : ActorMethod<[GestureId], ExternalBlob>,
  'getMusicByCreator' : ActorMethod<[Principal], Array<BackgroundMusic>>,
  'getSceneConfig' : ActorMethod<[SceneConfigId], SceneConfig>,
  'getSceneConfigsByCreator' : ActorMethod<[Principal], Array<SceneConfig>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[VideoId], Video>,
  'getVideosByCreator' : ActorMethod<[Principal], Array<Video>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processAvatarUpload' : ActorMethod<[AvatarMetadata, ExternalBlob], Avatar>,
  'registerAvatar' : ActorMethod<[Avatar], undefined>,
  'removeAssignedAvatar' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAudioMetadata' : ActorMethod<[AudioId, AudioMetadata], undefined>,
  'updateEmotion' : ActorMethod<[EmotionId, Emotion], undefined>,
  'updateGesture' : ActorMethod<[GestureId, Gesture], undefined>,
  'updateMusicMetadata' : ActorMethod<
    [MusicId, BackgroundMusicMetadata],
    undefined
  >,
  'updateSceneConfig' : ActorMethod<[SceneConfigId, SceneConfig], undefined>,
  'updateVideoMetadata' : ActorMethod<[VideoId, VideoMetadata], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];