/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    metadata: VideoMetadata;
    videoBlob: ExternalBlob;
}
export interface UserProfile {
    name: string;
    avatarId?: string;
}
export interface VisualEffect {
    startTime: bigint;
    duration: bigint;
    effectType: VisualEffectType;
    intensity: bigint;
}
export interface VideoFormat {
    codec: string;
    compatibleBrowsers: Array<string>;
    mimeType: string;
    resolution: [bigint, bigint];
    extension: string;
    bitrate: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type AvatarId = string;
export interface GestureCue {
    time: number;
    gesture: string;
}
export interface Gesture {
    id: GestureId;
    animationClip: ExternalBlob;
    name: string;
    createdBy: Principal;
    description: string;
    uploadDate: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type GestureId = string;
export interface Emotion {
    id: EmotionId;
    name: string;
    createdBy: Principal;
    description: string;
    uploadDate: bigint;
    intensityRange: [bigint, bigint];
}
export type VideoId = string;
export interface BackgroundMusicMetadata {
    id: MusicId;
    duration: bigint;
    createdBy: Principal;
    genre: string;
    uploadDate: bigint;
    videoId: VideoId;
}
export type SceneConfigId = string;
export interface AudioMetadata {
    id: AudioId;
    duration: bigint;
    createdBy: Principal;
    language: string;
    speakerId: Principal;
    uploadDate: bigint;
    videoId: VideoId;
}
export interface Avatar {
    avatarMetadata: AvatarMetadata;
    fileBlob: ExternalBlob;
}
export type MusicId = string;
export interface AvatarMetadata {
    id: AvatarId;
    isValidated: boolean;
    validationResults: string;
    name: string;
    createdBy: Principal;
    description: string;
    filePath: string;
    uploadDate: bigint;
}
export type EmotionId = string;
export interface SceneConfig {
    id: SceneConfigId;
    createdBy: Principal;
    sceneData: string;
    uploadDate: bigint;
    videoId: VideoId;
}
export interface Audio {
    metadata: AudioMetadata;
    audioBlob: ExternalBlob;
}
export interface EmotionTimeline {
    emotion: string;
    time: number;
    intensity: number;
}
export interface BackgroundMusic {
    metadata: BackgroundMusicMetadata;
    musicBlob: ExternalBlob;
}
export interface VideoMetadata {
    id: VideoId;
    title: string;
    duration: bigint;
    createdBy: Principal;
    description: string;
    visuals: Array<VisualEffect>;
    uploadDate: bigint;
    format: VideoFormat;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type AudioId = string;
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VisualEffectType {
    particle = "particle",
    lighting = "lighting",
    colorGrading = "colorGrading",
    depth = "depth",
    reflection = "reflection"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAudio(audio: Audio): Promise<void>;
    addBackgroundMusic(music: BackgroundMusic): Promise<void>;
    addEmotion(emotion: Emotion): Promise<void>;
    addGesture(gesture: Gesture): Promise<void>;
    addSceneConfig(config: SceneConfig): Promise<void>;
    addVideo(video: Video): Promise<void>;
    assignAvatarToUser(userId: Principal, avatarId: AvatarId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAvatar(id: AvatarId): Promise<void>;
    findVideosByTitle(title: string): Promise<Array<Video>>;
    generateEmotionTimeline(_narrationText: string): Promise<Array<EmotionTimeline>>;
    generateGestureTimeline(_narrationText: string): Promise<Array<GestureCue>>;
    getAllAudioSorted(): Promise<Array<Audio>>;
    getAllAvatars(): Promise<Array<Avatar>>;
    getAllEmotions(): Promise<Array<Emotion>>;
    getAllGestures(): Promise<Array<Gesture>>;
    getAllMusicSorted(): Promise<Array<BackgroundMusic>>;
    getAllSceneConfigsSorted(): Promise<Array<SceneConfig>>;
    getAllVideosSorted(): Promise<Array<Video>>;
    getAudio(id: AudioId): Promise<Audio>;
    getAudioByCreator(creator: Principal): Promise<Array<Audio>>;
    getAvailableEmotions(): Promise<Array<string>>;
    getAvailableGestures(): Promise<Array<string>>;
    getAvatar(id: AvatarId): Promise<Avatar | null>;
    getBackgroundMusic(id: MusicId): Promise<BackgroundMusic>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEmotion(id: EmotionId): Promise<Emotion | null>;
    getGesture(id: GestureId): Promise<Gesture | null>;
    getGestureAnimation(gestureId: GestureId): Promise<ExternalBlob>;
    getMusicByCreator(creator: Principal): Promise<Array<BackgroundMusic>>;
    getSceneConfig(id: SceneConfigId): Promise<SceneConfig>;
    getSceneConfigsByCreator(creator: Principal): Promise<Array<SceneConfig>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideo(id: VideoId): Promise<Video>;
    getVideosByCreator(creator: Principal): Promise<Array<Video>>;
    isCallerAdmin(): Promise<boolean>;
    processAvatarUpload(metadata: AvatarMetadata, fileBlob: ExternalBlob): Promise<Avatar>;
    registerAvatar(avatar: Avatar): Promise<void>;
    removeAssignedAvatar(userId: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAudioMetadata(id: AudioId, newMetadata: AudioMetadata): Promise<void>;
    updateEmotion(id: EmotionId, updatedEmotion: Emotion): Promise<void>;
    updateGesture(id: GestureId, updatedGesture: Gesture): Promise<void>;
    updateMusicMetadata(id: MusicId, newMetadata: BackgroundMusicMetadata): Promise<void>;
    updateSceneConfig(id: SceneConfigId, newConfig: SceneConfig): Promise<void>;
    updateVideoMetadata(id: VideoId, newMetadata: VideoMetadata): Promise<void>;
}
import type { Audio as _Audio, AudioMetadata as _AudioMetadata, Avatar as _Avatar, AvatarMetadata as _AvatarMetadata, BackgroundMusic as _BackgroundMusic, BackgroundMusicMetadata as _BackgroundMusicMetadata, Emotion as _Emotion, ExternalBlob as _ExternalBlob, Gesture as _Gesture, GestureId as _GestureId, UserProfile as _UserProfile, UserRole as _UserRole, Video as _Video, VideoFormat as _VideoFormat, VideoId as _VideoId, VideoMetadata as _VideoMetadata, VisualEffect as _VisualEffect, VisualEffectType as _VisualEffectType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAudio(arg0: Audio): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAudio(await to_candid_Audio_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAudio(await to_candid_Audio_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addBackgroundMusic(arg0: BackgroundMusic): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBackgroundMusic(await to_candid_BackgroundMusic_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBackgroundMusic(await to_candid_BackgroundMusic_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addEmotion(arg0: Emotion): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmotion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmotion(arg0);
            return result;
        }
    }
    async addGesture(arg0: Gesture): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGesture(await to_candid_Gesture_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGesture(await to_candid_Gesture_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSceneConfig(arg0: SceneConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSceneConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSceneConfig(arg0);
            return result;
        }
    }
    async addVideo(arg0: Video): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideo(await to_candid_Video_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideo(await to_candid_Video_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignAvatarToUser(arg0: Principal, arg1: AvatarId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignAvatarToUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignAvatarToUser(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAvatar(arg0: AvatarId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAvatar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAvatar(arg0);
            return result;
        }
    }
    async findVideosByTitle(arg0: string): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.findVideosByTitle(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findVideosByTitle(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateEmotionTimeline(arg0: string): Promise<Array<EmotionTimeline>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateEmotionTimeline(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateEmotionTimeline(arg0);
            return result;
        }
    }
    async generateGestureTimeline(arg0: string): Promise<Array<GestureCue>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateGestureTimeline(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateGestureTimeline(arg0);
            return result;
        }
    }
    async getAllAudioSorted(): Promise<Array<Audio>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAudioSorted();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAudioSorted();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAvatars(): Promise<Array<Avatar>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAvatars();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAvatars();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmotions(): Promise<Array<Emotion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmotions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmotions();
            return result;
        }
    }
    async getAllGestures(): Promise<Array<Gesture>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGestures();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGestures();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMusicSorted(): Promise<Array<BackgroundMusic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMusicSorted();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMusicSorted();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSceneConfigsSorted(): Promise<Array<SceneConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSceneConfigsSorted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSceneConfigsSorted();
            return result;
        }
    }
    async getAllVideosSorted(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideosSorted();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideosSorted();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAudio(arg0: AudioId): Promise<Audio> {
        if (this.processError) {
            try {
                const result = await this.actor.getAudio(arg0);
                return from_candid_Audio_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAudio(arg0);
            return from_candid_Audio_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAudioByCreator(arg0: Principal): Promise<Array<Audio>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAudioByCreator(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAudioByCreator(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableEmotions(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableEmotions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableEmotions();
            return result;
        }
    }
    async getAvailableGestures(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableGestures();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableGestures();
            return result;
        }
    }
    async getAvatar(arg0: AvatarId): Promise<Avatar | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvatar(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvatar(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBackgroundMusic(arg0: MusicId): Promise<BackgroundMusic> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackgroundMusic(arg0);
                return from_candid_BackgroundMusic_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackgroundMusic(arg0);
            return from_candid_BackgroundMusic_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmotion(arg0: EmotionId): Promise<Emotion | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmotion(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmotion(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGesture(arg0: GestureId): Promise<Gesture | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGesture(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGesture(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGestureAnimation(arg0: GestureId): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.getGestureAnimation(arg0);
                return from_candid_ExternalBlob_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGestureAnimation(arg0);
            return from_candid_ExternalBlob_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMusicByCreator(arg0: Principal): Promise<Array<BackgroundMusic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMusicByCreator(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMusicByCreator(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSceneConfig(arg0: SceneConfigId): Promise<SceneConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getSceneConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSceneConfig(arg0);
            return result;
        }
    }
    async getSceneConfigsByCreator(arg0: Principal): Promise<Array<SceneConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSceneConfigsByCreator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSceneConfigsByCreator(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideo(arg0: VideoId): Promise<Video> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_Video_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_Video_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideosByCreator(arg0: Principal): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByCreator(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByCreator(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async processAvatarUpload(arg0: AvatarMetadata, arg1: ExternalBlob): Promise<Avatar> {
        if (this.processError) {
            try {
                const result = await this.actor.processAvatarUpload(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Avatar_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processAvatarUpload(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Avatar_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerAvatar(arg0: Avatar): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAvatar(await to_candid_Avatar_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAvatar(await to_candid_Avatar_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async removeAssignedAvatar(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAssignedAvatar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAssignedAvatar(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n60(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n60(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAudioMetadata(arg0: AudioId, arg1: AudioMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAudioMetadata(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAudioMetadata(arg0, arg1);
            return result;
        }
    }
    async updateEmotion(arg0: EmotionId, arg1: Emotion): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmotion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmotion(arg0, arg1);
            return result;
        }
    }
    async updateGesture(arg0: GestureId, arg1: Gesture): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGesture(arg0, await to_candid_Gesture_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGesture(arg0, await to_candid_Gesture_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMusicMetadata(arg0: MusicId, arg1: BackgroundMusicMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMusicMetadata(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMusicMetadata(arg0, arg1);
            return result;
        }
    }
    async updateSceneConfig(arg0: SceneConfigId, arg1: SceneConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSceneConfig(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSceneConfig(arg0, arg1);
            return result;
        }
    }
    async updateVideoMetadata(arg0: VideoId, arg1: VideoMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideoMetadata(arg0, to_candid_VideoMetadata_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideoMetadata(arg0, to_candid_VideoMetadata_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_Audio_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Audio): Promise<Audio> {
    return await from_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_Avatar_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Avatar): Promise<Avatar> {
    return await from_candid_record_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_BackgroundMusic_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BackgroundMusic): Promise<BackgroundMusic> {
    return await from_candid_record_n48(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Gesture_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gesture): Promise<Gesture> {
    return await from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_VideoMetadata_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoMetadata): VideoMetadata {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_Video_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Promise<Video> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_VisualEffectType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisualEffectType): VisualEffectType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_VisualEffect_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisualEffect): VisualEffect {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Avatar]): Promise<Avatar | null> {
    return value.length === 0 ? null : await from_candid_Avatar_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n51(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Emotion]): Emotion | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Gesture]): Promise<Gesture | null> {
    return value.length === 0 ? null : await from_candid_Gesture_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metadata: _VideoMetadata;
    videoBlob: _ExternalBlob;
}): Promise<{
    metadata: VideoMetadata;
    videoBlob: ExternalBlob;
}> {
    return {
        metadata: from_candid_VideoMetadata_n29(_uploadFile, _downloadFile, value.metadata),
        videoBlob: await from_candid_ExternalBlob_n36(_uploadFile, _downloadFile, value.videoBlob)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    title: string;
    duration: bigint;
    createdBy: Principal;
    description: string;
    visuals: Array<_VisualEffect>;
    uploadDate: bigint;
    format: _VideoFormat;
}): {
    id: VideoId;
    title: string;
    duration: bigint;
    createdBy: Principal;
    description: string;
    visuals: Array<VisualEffect>;
    uploadDate: bigint;
    format: VideoFormat;
} {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        createdBy: value.createdBy,
        description: value.description,
        visuals: from_candid_vec_n31(_uploadFile, _downloadFile, value.visuals),
        uploadDate: value.uploadDate,
        format: value.format
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    duration: bigint;
    effectType: _VisualEffectType;
    intensity: bigint;
}): {
    startTime: bigint;
    duration: bigint;
    effectType: VisualEffectType;
    intensity: bigint;
} {
    return {
        startTime: value.startTime,
        duration: value.duration,
        effectType: from_candid_VisualEffectType_n34(_uploadFile, _downloadFile, value.effectType),
        intensity: value.intensity
    };
}
async function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metadata: _AudioMetadata;
    audioBlob: _ExternalBlob;
}): Promise<{
    metadata: AudioMetadata;
    audioBlob: ExternalBlob;
}> {
    return {
        metadata: value.metadata,
        audioBlob: await from_candid_ExternalBlob_n36(_uploadFile, _downloadFile, value.audioBlob)
    };
}
async function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    avatarMetadata: _AvatarMetadata;
    fileBlob: _ExternalBlob;
}): Promise<{
    avatarMetadata: AvatarMetadata;
    fileBlob: ExternalBlob;
}> {
    return {
        avatarMetadata: value.avatarMetadata,
        fileBlob: await from_candid_ExternalBlob_n36(_uploadFile, _downloadFile, value.fileBlob)
    };
}
async function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GestureId;
    animationClip: _ExternalBlob;
    name: string;
    createdBy: Principal;
    description: string;
    uploadDate: bigint;
}): Promise<{
    id: GestureId;
    animationClip: ExternalBlob;
    name: string;
    createdBy: Principal;
    description: string;
    uploadDate: bigint;
}> {
    return {
        id: value.id,
        animationClip: await from_candid_ExternalBlob_n36(_uploadFile, _downloadFile, value.animationClip),
        name: value.name,
        createdBy: value.createdBy,
        description: value.description,
        uploadDate: value.uploadDate
    };
}
async function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metadata: _BackgroundMusicMetadata;
    musicBlob: _ExternalBlob;
}): Promise<{
    metadata: BackgroundMusicMetadata;
    musicBlob: ExternalBlob;
}> {
    return {
        metadata: value.metadata,
        musicBlob: await from_candid_ExternalBlob_n36(_uploadFile, _downloadFile, value.musicBlob)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    avatarId: [] | [string];
}): {
    name: string;
    avatarId?: string;
} {
    return {
        name: value.name,
        avatarId: record_opt_to_undefined(from_candid_opt_n53(_uploadFile, _downloadFile, value.avatarId))
    };
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    particle: null;
} | {
    lighting: null;
} | {
    colorGrading: null;
} | {
    depth: null;
} | {
    reflection: null;
}): VisualEffectType {
    return "particle" in value ? VisualEffectType.particle : "lighting" in value ? VisualEffectType.lighting : "colorGrading" in value ? VisualEffectType.colorGrading : "depth" in value ? VisualEffectType.depth : "reflection" in value ? VisualEffectType.reflection : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Promise<Array<Video>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Video_n27(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VisualEffect>): Array<VisualEffect> {
    return value.map((x)=>from_candid_VisualEffect_n32(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Audio>): Promise<Array<Audio>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Audio_n38(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Avatar>): Promise<Array<Avatar>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Avatar_n41(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Gesture>): Promise<Array<Gesture>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Gesture_n44(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BackgroundMusic>): Promise<Array<BackgroundMusic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BackgroundMusic_n47(_uploadFile, _downloadFile, x)));
}
async function to_candid_Audio_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Audio): Promise<_Audio> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_Avatar_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Avatar): Promise<_Avatar> {
    return await to_candid_record_n59(_uploadFile, _downloadFile, value);
}
async function to_candid_BackgroundMusic_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BackgroundMusic): Promise<_BackgroundMusic> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Gesture_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gesture): Promise<_Gesture> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_VideoMetadata_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoMetadata): _VideoMetadata {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_Video_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Video): Promise<_Video> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_VisualEffectType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisualEffectType): _VisualEffectType {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_VisualEffect_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisualEffect): _VisualEffect {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metadata: BackgroundMusicMetadata;
    musicBlob: ExternalBlob;
}): Promise<{
    metadata: _BackgroundMusicMetadata;
    musicBlob: _ExternalBlob;
}> {
    return {
        metadata: value.metadata,
        musicBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.musicBlob)
    };
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: GestureId;
    animationClip: ExternalBlob;
    name: string;
    createdBy: Principal;
    description: string;
    uploadDate: bigint;
}): Promise<{
    id: _GestureId;
    animationClip: _ExternalBlob;
    name: string;
    createdBy: Principal;
    description: string;
    uploadDate: bigint;
}> {
    return {
        id: value.id,
        animationClip: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.animationClip),
        name: value.name,
        createdBy: value.createdBy,
        description: value.description,
        uploadDate: value.uploadDate
    };
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metadata: VideoMetadata;
    videoBlob: ExternalBlob;
}): Promise<{
    metadata: _VideoMetadata;
    videoBlob: _ExternalBlob;
}> {
    return {
        metadata: to_candid_VideoMetadata_n17(_uploadFile, _downloadFile, value.metadata),
        videoBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.videoBlob)
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: VideoId;
    title: string;
    duration: bigint;
    createdBy: Principal;
    description: string;
    visuals: Array<VisualEffect>;
    uploadDate: bigint;
    format: VideoFormat;
}): {
    id: _VideoId;
    title: string;
    duration: bigint;
    createdBy: Principal;
    description: string;
    visuals: Array<_VisualEffect>;
    uploadDate: bigint;
    format: _VideoFormat;
} {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        createdBy: value.createdBy,
        description: value.description,
        visuals: to_candid_vec_n19(_uploadFile, _downloadFile, value.visuals),
        uploadDate: value.uploadDate,
        format: value.format
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    duration: bigint;
    effectType: VisualEffectType;
    intensity: bigint;
}): {
    startTime: bigint;
    duration: bigint;
    effectType: _VisualEffectType;
    intensity: bigint;
} {
    return {
        startTime: value.startTime,
        duration: value.duration,
        effectType: to_candid_VisualEffectType_n22(_uploadFile, _downloadFile, value.effectType),
        intensity: value.intensity
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    avatarMetadata: AvatarMetadata;
    fileBlob: ExternalBlob;
}): Promise<{
    avatarMetadata: _AvatarMetadata;
    fileBlob: _ExternalBlob;
}> {
    return {
        avatarMetadata: value.avatarMetadata,
        fileBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.fileBlob)
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    avatarId?: string;
}): {
    name: string;
    avatarId: [] | [string];
} {
    return {
        name: value.name,
        avatarId: value.avatarId ? candid_some(value.avatarId) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metadata: AudioMetadata;
    audioBlob: ExternalBlob;
}): Promise<{
    metadata: _AudioMetadata;
    audioBlob: _ExternalBlob;
}> {
    return {
        metadata: value.metadata,
        audioBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.audioBlob)
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisualEffectType): {
    particle: null;
} | {
    lighting: null;
} | {
    colorGrading: null;
} | {
    depth: null;
} | {
    reflection: null;
} {
    return value == VisualEffectType.particle ? {
        particle: null
    } : value == VisualEffectType.lighting ? {
        lighting: null
    } : value == VisualEffectType.colorGrading ? {
        colorGrading: null
    } : value == VisualEffectType.depth ? {
        depth: null
    } : value == VisualEffectType.reflection ? {
        reflection: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<VisualEffect>): Array<_VisualEffect> {
    return value.map((x)=>to_candid_VisualEffect_n20(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
